import { motion, useInView } from 'framer-motion';
import { useRef } from 'react';
import { Link } from 'react-router-dom';
import {
    FileText, Code2, Users, Brain, Mic, Zap,
    BarChart3, Trophy, Star, Shield, CheckCircle, Sliders, ArrowRight
} from 'lucide-react';

const features = [
    { icon: FileText, title: 'Resume-Based Questions', desc: 'AI reads your PDF resume and crafts hyper-personalized questions targeting your exact tech stack and experience.', tag: 'Smart' },
    { icon: Code2, title: 'DSA Interview Mode', desc: 'Cover arrays, trees, graphs, DP, complexity analysis and get follow-up drill questions from the AI.', tag: 'Coding' },
    { icon: Users, title: 'HR Interview Mode', desc: 'Behavioral questions, STAR method scoring, confidence measurement and tone analysis.', tag: 'Soft Skills' },
    { icon: Brain, title: 'AI Voice Interviewer', desc: 'Realistic text-to-speech questions with natural pauses — exactly like a real phone screen.', tag: 'Voice' },
    { icon: Mic, title: 'Speech-to-Text Answers', desc: 'Speak your answers naturally. The browser transcribes in real time — no extra setup needed.', tag: 'Voice' },
    { icon: Zap, title: 'Real-Time Evaluation', desc: 'Each answer scores 0‑10 within seconds — strengths, weaknesses, and an ideal answer explanation.', tag: 'AI' },
    { icon: BarChart3, title: 'Performance Analytics', desc: 'Beautiful dashboards show DSA vs HR scores, monthly progress, and a weakness heatmap.', tag: 'Analytics' },
    { icon: Trophy, title: 'Leaderboard System', desc: 'Compete globally or in DSA / HR categories. Weekly boards reset every Sunday.', tag: 'Social' },
    { icon: Star, title: 'AI Improvement Plan', desc: '7-day personalized study plan with exercises, resources, and practice problems generated by GPT-4.', tag: 'AI' },
    { icon: FileText, title: 'PDF Report Generation', desc: 'Download a branded professional PDF with full score breakdown and improvement roadmap.', tag: 'Reports' },
    { icon: Shield, title: 'Role-Based Dashboard', desc: 'Separate experiences for candidates and admins — with granular access control using JWT.', tag: 'Security' },
    { icon: Sliders, title: 'Custom Interview Mode', desc: 'Choose difficulty, category, and any question count from 5 to 20 for targeted practice.', tag: 'Flexible' },
];

const tagColors = {
    Smart: { bg: 'rgba(124,58,237,0.08)', color: '#7C3AED' },
    Coding: { bg: 'rgba(5,150,105,0.08)', color: '#059669' },
    'Soft Skills': { bg: 'rgba(217,119,6,0.08)', color: '#D97706' },
    Voice: { bg: 'rgba(255,46,99,0.08)', color: '#FF2E63' },
    AI: { bg: 'rgba(2,132,199,0.08)', color: '#0284C7' },
    Analytics: { bg: 'rgba(236,72,153,0.08)', color: '#EC4899' },
    Social: { bg: 'rgba(245,158,11,0.08)', color: '#F59E0B' },
    Reports: { bg: 'rgba(99,102,241,0.08)', color: '#6366F1' },
    Security: { bg: 'rgba(16,185,129,0.08)', color: '#10B981' },
    Flexible: { bg: 'rgba(239,68,68,0.08)', color: '#EF4444' },
};

function FeatureCard({ feature, index }) {
    const ref = useRef(null);
    const inView = useInView(ref, { once: true, margin: '-60px' });
    const tag = tagColors[feature.tag] || tagColors.AI;

    return (
        <motion.div ref={ref}
            initial={{ opacity: 0, y: 40 }}
            animate={inView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.5, delay: (index % 3) * 0.1, ease: 'easeOut' }}
            className="glass-card card-hover pink-shadow rounded-3xl p-6 flex flex-col group relative overflow-hidden">
            {/* Shimmer overlay on hover */}
            <div className="absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity duration-500 shimmer rounded-3xl pointer-events-none" />

            <div className="flex items-start justify-between mb-4">
                <div className="w-12 h-12 rounded-2xl btn-gradient flex items-center justify-center group-hover:scale-110 transition-transform duration-300 flex-shrink-0">
                    <feature.icon size={20} color="white" />
                </div>
                <span className="text-xs font-bold px-2.5 py-1 rounded-full" style={{ background: tag.bg, color: tag.color }}>
                    {feature.tag}
                </span>
            </div>
            <h3 className="font-bold text-gray-900 text-base mb-2 group-hover:text-pink-600 transition-colors">{feature.title}</h3>
            <p className="text-sm text-gray-500 leading-relaxed flex-1">{feature.desc}</p>
        </motion.div>
    );
}

export default function Features() {
    return (
        <div className="min-h-screen relative overflow-hidden">
            {/* Background orbs */}
            <div className="orb w-[500px] h-[500px] bg-pink-200" style={{ top: '-10%', right: '-10%', opacity: 0.15 }} />
            <div className="orb w-[400px] h-[400px] bg-red-200" style={{ bottom: '5%', left: '-8%', opacity: 0.12 }} />

            {/* Hero */}
            <div className="section-hero relative z-10 text-center px-4">
                <motion.div initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }}>
                    <div className="stat-pill mx-auto mb-6">✨ 12 Powerful Features</div>
                    <h1 className="text-4xl sm:text-5xl lg:text-6xl font-black text-gray-900 mb-5 leading-tight">
                        Everything You Need<br />to <span className="gradient-text">Succeed</span>
                    </h1>
                    <p className="text-gray-500 text-lg max-w-2xl mx-auto mb-10">
                        One platform to simulate, evaluate, and master every type of technical and behavioral interview.
                    </p>
                    <div className="flex flex-wrap justify-center gap-3">
                        <Link to="/signup" className="btn-gradient px-8 py-3.5 rounded-2xl text-white font-bold flex items-center gap-2 text-sm">
                            Get Started Free <ArrowRight size={16} />
                        </Link>
                        <Link to="/how-it-works" className="btn-outline px-8 py-3.5 rounded-2xl font-bold text-sm">
                            See How It Works
                        </Link>
                    </div>
                </motion.div>
            </div>

            {/* Feature grid */}
            <div className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pb-24">
                <div className="feature-grid">
                    {features.map((f, i) => <FeatureCard key={f.title} feature={f} index={i} />)}
                </div>
            </div>
        </div>
    );
}
