const PDFDocument = require('pdfkit');
const Interview = require('../models/Interview');

const generateReport = async (req, res) => {
    const interview = await Interview.findById(req.params.id).populate('userId', 'name email').populate('resumeId', 'originalName skills');
    if (!interview) return res.status(404).json({ message: 'Interview not found' });
    if (interview.userId._id.toString() !== req.user._id.toString() && req.user.role !== 'admin')
        return res.status(403).json({ message: 'Not authorized' });

    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=InterviewReport-${interview._id}.pdf`);
    doc.pipe(res);

    // Header
    doc.rect(0, 0, doc.page.width, 80).fill('#FF2E63');
    doc.fill('#ffffff').fontSize(24).font('Helvetica-Bold').text('InterviewAI - Performance Report', 50, 25);
    doc.fill('#ffccdd').fontSize(10).text('AI-Powered Interview Simulation Platform', 50, 52);

    doc.moveDown(2);

    // Candidate Info
    doc.fill('#111111').fontSize(14).font('Helvetica-Bold').text('Candidate Information', 50, 100);
    doc.moveTo(50, 117).lineTo(545, 117).strokeColor('#FF2E63').lineWidth(1).stroke();

    doc.fontSize(11).font('Helvetica').fill('#333333');
    doc.text(`Name: ${interview.userId.name}`, 50, 125);
    doc.text(`Email: ${interview.userId.email}`, 50, 142);
    doc.text(`Interview Mode: ${interview.mode}`, 50, 159);
    doc.text(`Difficulty: ${interview.difficulty}`, 50, 176);
    doc.text(`Date: ${new Date(interview.createdAt).toLocaleDateString()}`, 50, 193);
    doc.text(`Duration: ${Math.round(interview.duration / 60)} minutes`, 50, 210);

    if (interview.resumeId) {
        doc.text(`Resume: ${interview.resumeId.originalName}`, 50, 227);
        doc.text(`Skills: ${interview.resumeId.skills.slice(0, 8).join(', ')}`, 50, 244);
    }

    // Score Summary
    doc.moveDown(1);
    const yStart = interview.resumeId ? 280 : 260;
    doc.fill('#111111').fontSize(14).font('Helvetica-Bold').text('Score Summary', 50, yStart);
    doc.moveTo(50, yStart + 17).lineTo(545, yStart + 17).strokeColor('#FF2E63').lineWidth(1).stroke();

    // Score box
    doc.rect(50, yStart + 25, 495, 60).fill('#fff5f7').stroke('#FF2E63');
    doc.fill('#FF2E63').fontSize(32).font('Helvetica-Bold').text(`${interview.percentage}%`, 60, yStart + 30);
    doc.fill('#333333').fontSize(11).font('Helvetica').text(`Total Score: ${interview.totalScore} / ${interview.maxPossibleScore}`, 200, yStart + 35);
    doc.text(`Questions Answered: ${interview.answers.length}`, 200, yStart + 52);
    doc.text(`Average Score: ${interview.answers.length ? (interview.totalScore / interview.answers.length).toFixed(1) : 0} / 10`, 200, yStart + 69);

    // Q&A Breakdown
    let y = yStart + 105;
    doc.fill('#111111').fontSize(14).font('Helvetica-Bold').text('Question-wise Breakdown', 50, y);
    y += 17;
    doc.moveTo(50, y).lineTo(545, y).strokeColor('#FF2E63').lineWidth(1).stroke();
    y += 10;

    interview.answers.forEach((ans, idx) => {
        if (y > 700) { doc.addPage(); y = 50; }

        doc.rect(50, y, 495, 1).fill('#eeeeee');
        y += 5;
        doc.fill('#FF2E63').fontSize(10).font('Helvetica-Bold').text(`Q${idx + 1}: `, 50, y, { continued: true });
        doc.fill('#111111').font('Helvetica').text(ans.questionText.substring(0, 100) + (ans.questionText.length > 100 ? '...' : ''));
        y += 15;
        doc.fill('#444444').fontSize(9).text(`Score: ${ans.score}/10  |  Confidence: ${ans.confidenceScore}/10  |  Communication: ${ans.communicationScore}/10`, 50, y);
        y += 13;
        if (ans.strengths.length > 0) {
            doc.fill('#16a34a').text(`✓ ${ans.strengths.slice(0, 2).join(' | ')}`, 50, y);
            y += 13;
        }
        if (ans.weaknesses.length > 0) {
            doc.fill('#dc2626').text(`✗ ${ans.weaknesses.slice(0, 2).join(' | ')}`, 50, y);
            y += 13;
        }
        y += 5;
    });

    // Improvement Plan
    if (interview.improvementPlan) {
        if (y > 650) { doc.addPage(); y = 50; }
        doc.fill('#111111').fontSize(14).font('Helvetica-Bold').text('AI Improvement Plan', 50, y);
        y += 17;
        doc.moveTo(50, y).lineTo(545, y).strokeColor('#FF2E63').lineWidth(1).stroke();
        y += 10;
        doc.fill('#333333').fontSize(10).font('Helvetica').text(interview.improvementPlan, 50, y, { width: 495 });
    }

    // Footer
    const pages = doc.bufferedPageRange();
    for (let i = pages.start; i < pages.start + pages.count; i++) {
        doc.switchToPage(i);
        doc.fill('#999999').fontSize(8).text('Generated by InterviewAI — AI-Powered Interview Platform', 50, doc.page.height - 35, { align: 'center' });
    }

    doc.end();
};

module.exports = { generateReport };
